name: Test Documentation
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - doc-fix

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yaml@master
    with:
      target: pluginplay_cxx_api
      dependencies: cmake doxygen sphinx
